/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andyyang_sliderecyclerview_JNIdebug */

#ifndef _Included_com_andyyang_sliderecyclerview_JNIdebug
#define _Included_com_andyyang_sliderecyclerview_JNIdebug
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andyyang_sliderecyclerview_JNIdebug
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_andyyang_sliderecyclerview_JNIdebug_hello
  (JNIEnv *, jclass);

/*
 * Class:     com_andyyang_sliderecyclerview_JNIdebug
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_andyyang_sliderecyclerview_JNIdebug_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
